import { createFileRoute, Link as RouterLink } from "@tanstack/react-router"

import { APP_NAME } from "@/components/Common/Logo"
import { Bullets, LegalPage, Section } from "@/components/Legal/LegalPage"

/**
 * The agreement between whoever runs this installation and whoever uses it.
 *
 * Written against what the product actually does — the limits it enforces, the
 * models it calls, the sharing it allows — rather than from a template. The
 * blanks are marked rather than guessed.
 */

export const Route = createFileRoute("/terms")({
  component: Terms,
  head: () => ({
    meta: [{ title: `Terms of Service - ${APP_NAME}` }],
  }),
})

function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      intro={
        <>
          These terms govern your use of {APP_NAME}. By creating an account or
          using the service you agree to them. If you are agreeing on behalf of
          an organisation, you confirm you may bind it.
        </>
      }
    >
      <Section id="service" title="What the service is">
        <p>
          {APP_NAME} is a knowledge base. You can write pages, upload documents,
          organise them into spaces and folders, search them, share them, and
          ask questions that are answered from them using AI models.
        </p>
        <p>
          It is provided by <strong>Shanaka Anuradha</strong>, Stuttgarter Str.
          15, 74074 Heilbronn, Germany ("we", "us"). You can reach us at{" "}
          <a href="mailto:admin@plusgpt.io">admin@plusgpt.io</a>; full provider
          details are on the <RouterLink to="/imprint">Imprint</RouterLink>.
        </p>
      </Section>

      <Section id="account" title="Your account">
        <Bullets
          items={[
            "You need a working email address, because signing in requires a code sent to it.",
            "You are responsible for what happens under your account, including anything done with an API key you created.",
            "Keep your password and your API keys to yourself. Tell us promptly if you think either has been exposed.",
            "One account is for one person. Sharing credentials is not on.",
          ]}
        />
      </Section>

      <Section id="your-content" title="Your content stays yours">
        <p>
          You keep every right you already had in what you write and upload. We
          claim no ownership of it.
        </p>
        <p>
          You give us only the permission the service needs in order to run: to
          store your content, index it, make it searchable, show it to the
          people you share it with, and send the relevant parts to a model
          provider so that questions can be answered and pages transcribed or
          translated. That permission exists only to operate the service, and it
          ends when you delete the content or close your account.
        </p>
        <p>
          You confirm you have the right to upload what you upload, and that
          doing so does not breach anybody else's rights or any duty of
          confidence you owe.
        </p>
      </Section>

      <Section id="ai" title="AI answers, and what they are worth">
        <p className="font-medium">
          Answers are generated by a language model and can be wrong.
        </p>
        <p>
          The service quotes the pages an answer was drawn from precisely so you
          can check it. Do not rely on an answer for anything that matters
          without reading the source. Nothing {APP_NAME} produces is legal,
          medical, financial or professional advice.
        </p>
        <p>
          Model output is not guaranteed to be unique; a model may generate
          similar text for other people asking similar questions.
        </p>
      </Section>

      <Section id="acceptable" title="What you may not do">
        <Bullets
          items={[
            "Upload content that is unlawful, or that you have no right to upload.",
            "Use the service to harass anybody, or to store material that sexualises children or incites violence.",
            "Try to get round access controls, sharing permissions, or the limits on your account.",
            "Probe, scan or overload the service, or automate use of it in a way that degrades it for others.",
            "Resell or repackage the service as your own without our written agreement.",
            "Use it to build a competing service, or to extract the underlying models.",
          ]}
        />
        <p>
          We may suspend or close an account that does any of these. Where it is
          reasonable to do so, we will say what happened first.
        </p>
      </Section>

      <Section id="limits" title="Limits">
        <p>
          Accounts have limits — on how many pages they may create, and on how
          widely a single page or space may be shared. Administrators of this
          installation set them, per person or per group. When you reach one,
          the service tells you the number and what to do about it.
        </p>
        <p>
          We may change limits, and will give reasonable notice before lowering
          one in a way that affects you.
        </p>
      </Section>

      <Section id="sharing" title="Sharing">
        <p>
          You decide who sees what. A public link makes a page readable by
          anyone holding it — treat it as public. Turning link sharing off and
          on again issues a new link and breaks the old one, which is the
          intended way to revoke access.
        </p>
        <p>
          Sharing something with somebody does not make us responsible for what
          they then do with it.
        </p>
      </Section>

      <Section id="availability" title="Availability">
        <p>
          We work to keep {APP_NAME} available and will give notice of planned
          maintenance where we can. We do not promise uninterrupted service, and
          the service is provided <strong>as is</strong> without warranties of
          any kind, to the fullest extent the law allows.
        </p>
        <p>
          Keep your own copies of anything you cannot afford to lose. The
          original of every file you upload is retained and can be downloaded at
          any time.
        </p>
      </Section>

      <Section id="liability" title="Liability">
        <p>
          Our liability is limited as far as German law permits, and no further.
          German law does not allow a blanket exclusion, so this clause says
          exactly where the line falls rather than pretending it is elsewhere.
        </p>
        <p className="font-medium">We are fully liable</p>
        <Bullets
          items={[
            "for damage caused intentionally or by gross negligence;",
            "for injury to life, body or health;",
            "under the German Product Liability Act (Produkthaftungsgesetz); and",
            "where we have given a guarantee or fraudulently concealed a defect.",
          ]}
        />
        <p className="font-medium">Otherwise</p>
        <p>
          For slight negligence we are liable only where we breach an obligation
          that is essential to the contract — one you must be able to rely on
          for the service to work at all — and then only for the loss typically
          foreseeable for this kind of service. All other liability for slight
          negligence is excluded, including for lost profits and for indirect or
          consequential loss.
        </p>
        <p>
          <strong>Keep your own copies.</strong> Our liability for lost or
          corrupted data is in any case limited to the effort of restoring it
          from a backup you have kept properly.
        </p>
        <p>
          These limits apply equally to our employees, agents and
          subcontractors. Nothing here affects your statutory rights as a
          consumer.
        </p>
      </Section>

      <Section id="ending" title="Ending it">
        <p>
          You may close your account at any time from <strong>Settings</strong>.
          Doing so deletes it and the pages only you could see. We may close or
          suspend an account for a serious or repeated breach of these terms, or
          if we stop offering the service — in which case we will give
          reasonable notice and a chance to export what you have.
        </p>
      </Section>

      <Section id="changes" title="Changes to these terms">
        <p>
          We may update these terms. If a change matters, we will tell you
          before it takes effect. Continuing to use the service after that means
          you accept the new version. The date at the top always reflects the
          current one.
        </p>
      </Section>

      <Section id="law" title="Governing law">
        <p>
          These terms are governed by the law of the{" "}
          <strong>Federal Republic of Germany</strong>, excluding the UN
          Convention on Contracts for the International Sale of Goods.
        </p>
        <p>
          If you are a merchant, a legal person under public law or a special
          fund under public law, the courts of{" "}
          <strong>Heilbronn, Germany</strong> have exclusive jurisdiction. If
          you are a consumer, you keep every protection the mandatory law of the
          country you live in gives you, and you may bring a claim there.
        </p>
        <p>
          The European Commission provides a platform for online dispute
          resolution at{" "}
          <a
            href="https://ec.europa.eu/consumers/odr"
            target="_blank"
            rel="noreferrer"
          >
            ec.europa.eu/consumers/odr
          </a>
          . We are not obliged, and are not willing, to take part in dispute
          resolution proceedings before a consumer arbitration board.
        </p>
        <p>
          How we handle your data is described in the{" "}
          <RouterLink to="/privacy">Privacy Policy</RouterLink>, which forms
          part of these terms.
        </p>
      </Section>
    </LegalPage>
  )
}
