// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    scope?: ApiKeyScope;
    /**
     * Expires In Days
     */
    expires_in_days?: number | null;
};

/**
 * ApiKeyCreated
 */
export type ApiKeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    scope: ApiKeyScope;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Key
     */
    key: string;
};

/**
 * ApiKeyPublic
 */
export type ApiKeyPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    scope: ApiKeyScope;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ApiKeyScope
 */
export type ApiKeyScope = 'read' | 'write';

/**
 * ApiKeyUpdate
 */
export type ApiKeyUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ApiKeysPublic
 */
export type ApiKeysPublic = {
    /**
     * Data
     */
    data: Array<ApiKeyPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AskAnswer
 */
export type AskAnswer = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
    /**
     * Citations
     */
    citations?: Array<AskCitation>;
    /**
     * Searched
     */
    searched?: number;
    /**
     * Used
     */
    used?: number;
    /**
     * Passages
     */
    passages?: number;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Model
     */
    model?: string;
    /**
     * Retrieval Ms
     */
    retrieval_ms?: number;
    /**
     * Took Ms
     */
    took_ms?: number;
};

/**
 * AskCitation
 *
 * One excerpt the model was given, numbered as it appears in the answer.
 */
export type AskCitation = {
    /**
     * Index
     */
    index: number;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug: string;
    /**
     * Namespace Name
     */
    namespace_name: string;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Chunk Index
     */
    chunk_index?: number | null;
    /**
     * Chunk Title
     */
    chunk_title?: string | null;
    /**
     * Score
     */
    score?: number;
    /**
     * Cited
     */
    cited?: boolean;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * AskRequest
 */
export type AskRequest = {
    /**
     * Q
     */
    q: string;
    /**
     * Namespace Id
     */
    namespace_id?: string | null;
    /**
     * Top K
     */
    top_k?: number | null;
};

/**
 * AttachmentPublic
 */
export type AttachmentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Document Id
     */
    document_id?: string | null;
    /**
     * Uploader Id
     */
    uploader_id?: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Download Url
     */
    download_url: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AttachmentsPublic
 */
export type AttachmentsPublic = {
    /**
     * Data
     */
    data: Array<AttachmentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_attachments-upload_attachment
 */
export type Body_attachments_upload_attachment = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Document Id
     */
    document_id?: string | null;
};

/**
 * Body_imports-create_import
 */
export type Body_imports_create_import = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ContentFormat
 */
export type ContentFormat = 'html' | 'markdown' | 'text';

/**
 * DocumentChunkPublic
 */
export type DocumentChunkPublic = {
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
    /**
     * Char Count
     */
    char_count: number;
    /**
     * Doc Version
     */
    doc_version: number;
};

/**
 * DocumentCreate
 */
export type DocumentCreate = {
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string;
    content_format?: ContentFormat;
};

/**
 * DocumentEmbeddingsPublic
 */
export type DocumentEmbeddingsPublic = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Embedding Version
     */
    embedding_version?: number | null;
    /**
     * Is Stale
     */
    is_stale: boolean;
    embedding_status: EmbeddingStatus;
    /**
     * Embedding Error
     */
    embedding_error?: string | null;
    /**
     * Embedding Attempts
     */
    embedding_attempts?: number;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Chunking Method
     */
    chunking_method?: string | null;
    /**
     * Embedding Updated At
     */
    embedding_updated_at?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
    current_job?: EmbeddingJobPublic | null;
    /**
     * Jobs
     */
    jobs?: Array<EmbeddingJobPublic>;
    /**
     * Chunks
     */
    chunks?: Array<DocumentChunkPublic>;
    /**
     * Kinds
     */
    kinds?: Array<string>;
};

/**
 * DocumentMove
 */
export type DocumentMove = {
    /**
     * Namespace Id
     */
    namespace_id?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
};

/**
 * DocumentPublic
 */
export type DocumentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Version
     */
    version: number;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Updated By
     */
    updated_by?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    embedding_status: EmbeddingStatus;
    /**
     * Embedding Version
     */
    embedding_version?: number | null;
    /**
     * Embedding Error
     */
    embedding_error?: string | null;
    /**
     * Embedding Attempts
     */
    embedding_attempts?: number;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Chunking Method
     */
    chunking_method?: string | null;
    /**
     * Embedding Updated At
     */
    embedding_updated_at?: string | null;
    /**
     * Is Stale
     */
    is_stale?: boolean;
    my_role?: ShareRole | null;
    /**
     * Source Attachment Id
     */
    source_attachment_id?: string | null;
    /**
     * Content Html
     */
    content_html: string;
    /**
     * Content Text
     */
    content_text: string;
    /**
     * Summary
     */
    summary?: string | null;
    updated_by_user?: UserRef | null;
    created_by_user?: UserRef | null;
    source_attachment?: AttachmentPublic | null;
};

/**
 * DocumentShareCreate
 */
export type DocumentShareCreate = {
    /**
     * Email
     */
    email: string;
    role?: ShareRole;
};

/**
 * DocumentSharePublic
 */
export type DocumentSharePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    user: UserRef;
    role: ShareRole;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * DocumentShareUpdate
 */
export type DocumentShareUpdate = {
    role: ShareRole;
};

/**
 * DocumentSharesPublic
 */
export type DocumentSharesPublic = {
    /**
     * Data
     */
    data: Array<DocumentSharePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentSummaryPublic
 *
 * Document metadata without content (lists, trees, search).
 */
export type DocumentSummaryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Version
     */
    version: number;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Updated By
     */
    updated_by?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    embedding_status: EmbeddingStatus;
    /**
     * Embedding Version
     */
    embedding_version?: number | null;
    /**
     * Embedding Error
     */
    embedding_error?: string | null;
    /**
     * Embedding Attempts
     */
    embedding_attempts?: number;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Chunking Method
     */
    chunking_method?: string | null;
    /**
     * Embedding Updated At
     */
    embedding_updated_at?: string | null;
    /**
     * Is Stale
     */
    is_stale?: boolean;
    my_role?: ShareRole | null;
    /**
     * Source Attachment Id
     */
    source_attachment_id?: string | null;
};

/**
 * DocumentUpdate
 */
export type DocumentUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    content_format?: ContentFormat;
    /**
     * Expected Version
     */
    expected_version?: number | null;
};

/**
 * DocumentsPublic
 */
export type DocumentsPublic = {
    /**
     * Data
     */
    data: Array<DocumentSummaryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EmbeddingJobPublic
 */
export type EmbeddingJobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Doc Version
     */
    doc_version: number;
    status: JobStatus;
    stage?: JobStage | null;
    /**
     * Progress
     */
    progress?: number;
    /**
     * Attempts
     */
    attempts?: number;
    /**
     * Max Attempts
     */
    max_attempts?: number;
    /**
     * Run After
     */
    run_after: string;
    /**
     * Cancel Requested
     */
    cancel_requested?: boolean;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Chunking Method
     */
    chunking_method?: string | null;
    /**
     * Chunk Count
     */
    chunk_count?: number | null;
    /**
     * Stats
     */
    stats?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * EmbeddingKind
 */
export type EmbeddingKind = 'document' | 'summary' | 'chunk';

/**
 * EmbeddingStatus
 */
export type EmbeddingStatus = 'pending' | 'chunking' | 'summarizing' | 'embedding' | 'ready' | 'failed';

/**
 * EmbeddingSummary
 *
 * Counts of accessible documents by embedding state (dashboard).
 */
export type EmbeddingSummary = {
    /**
     * Total
     */
    total?: number;
    /**
     * Pending
     */
    pending?: number;
    /**
     * In Progress
     */
    in_progress?: number;
    /**
     * Ready
     */
    ready?: number;
    /**
     * Stale
     */
    stale?: number;
    /**
     * Failed
     */
    failed?: number;
    /**
     * Queued Jobs
     */
    queued_jobs?: number;
    /**
     * Running Jobs
     */
    running_jobs?: number;
};

/**
 * FolderContents
 */
export type FolderContents = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Folders
     */
    folders?: Array<FolderPublic>;
    /**
     * Documents
     */
    documents?: Array<DocumentSummaryPublic>;
    /**
     * Path
     */
    path?: Array<FolderPublic>;
};

/**
 * FolderCreate
 */
export type FolderCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * FolderPublic
 */
export type FolderPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * FolderUpdate
 */
export type FolderUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Move To Root
     */
    move_to_root?: boolean;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthReport
 */
export type HealthReport = {
    /**
     * Status
     */
    status: string;
    /**
     * Services
     */
    services: {
        [key: string]: ServiceHealth;
    };
    /**
     * Checked At
     */
    checked_at: string;
};

/**
 * ImportJobPublic
 */
export type ImportJobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Document Id
     */
    document_id?: string | null;
    /**
     * Attachment Id
     */
    attachment_id?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    status: ImportStatus;
    parser?: ImportParser | null;
    /**
     * Pages Total
     */
    pages_total?: number;
    /**
     * Pages Done
     */
    pages_done?: number;
    /**
     * Attempts
     */
    attempts?: number;
    /**
     * Max Attempts
     */
    max_attempts?: number;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ImportJobsPublic
 */
export type ImportJobsPublic = {
    /**
     * Data
     */
    data: Array<ImportJobPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ImportParser
 */
export type ImportParser = 'mineru' | 'llm';

/**
 * ImportStatus
 */
export type ImportStatus = 'queued' | 'rendering' | 'parsing' | 'creating' | 'done' | 'failed' | 'cancelled';

/**
 * JobStage
 */
export type JobStage = 'claimed' | 'loading' | 'chunking' | 'summarizing' | 'embedding' | 'writing' | 'done';

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled' | 'superseded';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NamespaceCreate
 */
export type NamespaceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Icon
     */
    icon?: string;
    /**
     * Color
     */
    color?: string;
};

/**
 * NamespaceMemberCreate
 */
export type NamespaceMemberCreate = {
    role?: NamespaceRole;
    /**
     * Email
     */
    email: string;
};

/**
 * NamespaceMemberPublic
 */
export type NamespaceMemberPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    user: UserRef;
    role: NamespaceRole;
    /**
     * Is Owner
     */
    is_owner?: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * NamespaceMemberUpdate
 */
export type NamespaceMemberUpdate = {
    role: NamespaceRole;
};

/**
 * NamespaceMembersPublic
 */
export type NamespaceMembersPublic = {
    /**
     * Data
     */
    data: Array<NamespaceMemberPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * NamespacePublic
 */
export type NamespacePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Icon
     */
    icon?: string;
    /**
     * Color
     */
    color?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Owner Id
     */
    owner_id: string;
    owner?: UserRef | null;
    my_role?: NamespaceRole | null;
    /**
     * Document Count
     */
    document_count?: number;
    /**
     * Member Count
     */
    member_count?: number;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * NamespaceRole
 */
export type NamespaceRole = 'viewer' | 'editor' | 'admin';

/**
 * NamespaceTree
 */
export type NamespaceTree = {
    namespace: NamespacePublic;
    /**
     * Folders
     */
    folders: Array<FolderPublic>;
    /**
     * Documents
     */
    documents: Array<DocumentSummaryPublic>;
};

/**
 * NamespaceUpdate
 */
export type NamespaceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Icon
     */
    icon?: string | null;
    /**
     * Color
     */
    color?: string | null;
};

/**
 * NamespacesPublic
 */
export type NamespacesPublic = {
    /**
     * Data
     */
    data: Array<NamespacePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RetrievalHit
 */
export type RetrievalHit = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug: string;
    /**
     * Namespace Name
     */
    namespace_name: string;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Score
     */
    score: number;
    /**
     * Snippet
     */
    snippet: string;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    embedding_status: EmbeddingStatus;
    /**
     * Matched Chunk Index
     */
    matched_chunk_index?: number | null;
    /**
     * Matched Chunk Title
     */
    matched_chunk_title?: string | null;
    /**
     * Sources
     */
    sources?: Array<RetrievalSourceHit>;
};

/**
 * RetrievalResults
 */
export type RetrievalResults = {
    /**
     * Data
     */
    data: Array<RetrievalHit>;
    /**
     * Count
     */
    count: number;
    /**
     * Query
     */
    query: string;
    /**
     * Query Tokens
     */
    query_tokens?: Array<string>;
    /**
     * Used Bm25
     */
    used_bm25: boolean;
    /**
     * Used Vector
     */
    used_vector: boolean;
    /**
     * Targets
     */
    targets?: Array<string>;
    /**
     * Rrf K
     */
    rrf_k: number;
    /**
     * Sources
     */
    sources?: Array<RetrievalSourceReport>;
    /**
     * Took Ms
     */
    took_ms?: number;
};

/**
 * RetrievalSourceHit
 *
 * Why one source matched a document.
 */
export type RetrievalSourceHit = {
    /**
     * Method
     */
    method: string;
    /**
     * Target
     */
    target: string;
    /**
     * Rank
     */
    rank: number;
    /**
     * Score
     */
    score: number;
    /**
     * Contribution
     */
    contribution: number;
    /**
     * Chunk Index
     */
    chunk_index?: number | null;
    /**
     * Chunk Title
     */
    chunk_title?: string | null;
};

/**
 * RetrievalSourceReport
 */
export type RetrievalSourceReport = {
    /**
     * Method
     */
    method: string;
    /**
     * Target
     */
    target: string;
    /**
     * Hits
     */
    hits: number;
    /**
     * Took Ms
     */
    took_ms: number;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * SearchResult
 */
export type SearchResult = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Namespace Slug
     */
    namespace_slug: string;
    /**
     * Namespace Name
     */
    namespace_name: string;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Snippet
     */
    snippet: string;
    /**
     * Rank
     */
    rank: number;
    /**
     * Updated At
     */
    updated_at?: string | null;
    embedding_status: EmbeddingStatus;
};

/**
 * SearchResults
 */
export type SearchResults = {
    /**
     * Data
     */
    data: Array<SearchResult>;
    /**
     * Count
     */
    count: number;
};

/**
 * ServiceHealth
 */
export type ServiceHealth = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * ShareRole
 */
export type ShareRole = 'viewer' | 'editor';

/**
 * SharedWithMe
 */
export type SharedWithMe = {
    /**
     * Namespaces
     */
    namespaces: Array<NamespacePublic>;
    /**
     * Documents
     */
    documents: Array<DocumentSummaryPublic>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRef
 *
 * Compact user reference embedded in other resources.
 */
export type UserRef = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkerPublic
 */
export type WorkerPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Hostname
     */
    hostname: string;
    /**
     * Pid
     */
    pid: number;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Heartbeat At
     */
    heartbeat_at: string;
    /**
     * Concurrency
     */
    concurrency: number;
    /**
     * Running Jobs
     */
    running_jobs: number;
    /**
     * Online
     */
    online: boolean;
};

/**
 * WorkersPublic
 */
export type WorkersPublic = {
    /**
     * Workers
     */
    workers: Array<WorkerPublic>;
    /**
     * Any Online
     */
    any_online: boolean;
    /**
     * Queued Jobs
     */
    queued_jobs: number;
    /**
     * Running Jobs
     */
    running_jobs: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type healthReadHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/';
};

export type healthReadHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthReport;
};

export type healthReadHealthResponse = healthReadHealthResponses[keyof healthReadHealthResponses];

export type namespacesReadNamespacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/namespaces/';
};

export type namespacesReadNamespacesResponses = {
    /**
     * Successful Response
     */
    200: NamespacesPublic;
};

export type namespacesReadNamespacesResponse = namespacesReadNamespacesResponses[keyof namespacesReadNamespacesResponses];

export type namespacesCreateNamespaceData = {
    body: NamespaceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/namespaces/';
};

export type namespacesCreateNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesCreateNamespaceError = namespacesCreateNamespaceErrors[keyof namespacesCreateNamespaceErrors];

export type namespacesCreateNamespaceResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type namespacesCreateNamespaceResponse = namespacesCreateNamespaceResponses[keyof namespacesCreateNamespaceResponses];

export type namespacesReadNamespaceBySlugData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/namespaces/by-slug/{slug}';
};

export type namespacesReadNamespaceBySlugErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesReadNamespaceBySlugError = namespacesReadNamespaceBySlugErrors[keyof namespacesReadNamespaceBySlugErrors];

export type namespacesReadNamespaceBySlugResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type namespacesReadNamespaceBySlugResponse = namespacesReadNamespaceBySlugResponses[keyof namespacesReadNamespaceBySlugResponses];

export type namespacesDeleteNamespaceData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}';
};

export type namespacesDeleteNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesDeleteNamespaceError = namespacesDeleteNamespaceErrors[keyof namespacesDeleteNamespaceErrors];

export type namespacesDeleteNamespaceResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type namespacesDeleteNamespaceResponse = namespacesDeleteNamespaceResponses[keyof namespacesDeleteNamespaceResponses];

export type namespacesReadNamespaceData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}';
};

export type namespacesReadNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesReadNamespaceError = namespacesReadNamespaceErrors[keyof namespacesReadNamespaceErrors];

export type namespacesReadNamespaceResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type namespacesReadNamespaceResponse = namespacesReadNamespaceResponses[keyof namespacesReadNamespaceResponses];

export type namespacesUpdateNamespaceData = {
    body: NamespaceUpdate;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}';
};

export type namespacesUpdateNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesUpdateNamespaceError = namespacesUpdateNamespaceErrors[keyof namespacesUpdateNamespaceErrors];

export type namespacesUpdateNamespaceResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type namespacesUpdateNamespaceResponse = namespacesUpdateNamespaceResponses[keyof namespacesUpdateNamespaceResponses];

export type namespacesReadNamespaceTreeData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/tree';
};

export type namespacesReadNamespaceTreeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesReadNamespaceTreeError = namespacesReadNamespaceTreeErrors[keyof namespacesReadNamespaceTreeErrors];

export type namespacesReadNamespaceTreeResponses = {
    /**
     * Successful Response
     */
    200: NamespaceTree;
};

export type namespacesReadNamespaceTreeResponse = namespacesReadNamespaceTreeResponses[keyof namespacesReadNamespaceTreeResponses];

export type namespacesReadNamespaceMembersData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/members';
};

export type namespacesReadNamespaceMembersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesReadNamespaceMembersError = namespacesReadNamespaceMembersErrors[keyof namespacesReadNamespaceMembersErrors];

export type namespacesReadNamespaceMembersResponses = {
    /**
     * Successful Response
     */
    200: NamespaceMembersPublic;
};

export type namespacesReadNamespaceMembersResponse = namespacesReadNamespaceMembersResponses[keyof namespacesReadNamespaceMembersResponses];

export type namespacesAddNamespaceMemberData = {
    body: NamespaceMemberCreate;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/members';
};

export type namespacesAddNamespaceMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesAddNamespaceMemberError = namespacesAddNamespaceMemberErrors[keyof namespacesAddNamespaceMemberErrors];

export type namespacesAddNamespaceMemberResponses = {
    /**
     * Successful Response
     */
    200: NamespaceMemberPublic;
};

export type namespacesAddNamespaceMemberResponse = namespacesAddNamespaceMemberResponses[keyof namespacesAddNamespaceMemberResponses];

export type namespacesRemoveNamespaceMemberData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/members/{user_id}';
};

export type namespacesRemoveNamespaceMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesRemoveNamespaceMemberError = namespacesRemoveNamespaceMemberErrors[keyof namespacesRemoveNamespaceMemberErrors];

export type namespacesRemoveNamespaceMemberResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type namespacesRemoveNamespaceMemberResponse = namespacesRemoveNamespaceMemberResponses[keyof namespacesRemoveNamespaceMemberResponses];

export type namespacesUpdateNamespaceMemberData = {
    body: NamespaceMemberUpdate;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/members/{user_id}';
};

export type namespacesUpdateNamespaceMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type namespacesUpdateNamespaceMemberError = namespacesUpdateNamespaceMemberErrors[keyof namespacesUpdateNamespaceMemberErrors];

export type namespacesUpdateNamespaceMemberResponses = {
    /**
     * Successful Response
     */
    200: NamespaceMemberPublic;
};

export type namespacesUpdateNamespaceMemberResponse = namespacesUpdateNamespaceMemberResponses[keyof namespacesUpdateNamespaceMemberResponses];

export type foldersCreateFolderData = {
    body: FolderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/folders/';
};

export type foldersCreateFolderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type foldersCreateFolderError = foldersCreateFolderErrors[keyof foldersCreateFolderErrors];

export type foldersCreateFolderResponses = {
    /**
     * Successful Response
     */
    200: FolderPublic;
};

export type foldersCreateFolderResponse = foldersCreateFolderResponses[keyof foldersCreateFolderResponses];

export type foldersDeleteFolderData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/v1/folders/{folder_id}';
};

export type foldersDeleteFolderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type foldersDeleteFolderError = foldersDeleteFolderErrors[keyof foldersDeleteFolderErrors];

export type foldersDeleteFolderResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type foldersDeleteFolderResponse = foldersDeleteFolderResponses[keyof foldersDeleteFolderResponses];

export type foldersReadFolderData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/v1/folders/{folder_id}';
};

export type foldersReadFolderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type foldersReadFolderError = foldersReadFolderErrors[keyof foldersReadFolderErrors];

export type foldersReadFolderResponses = {
    /**
     * Successful Response
     */
    200: FolderContents;
};

export type foldersReadFolderResponse = foldersReadFolderResponses[keyof foldersReadFolderResponses];

export type foldersUpdateFolderData = {
    body: FolderUpdate;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/v1/folders/{folder_id}';
};

export type foldersUpdateFolderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type foldersUpdateFolderError = foldersUpdateFolderErrors[keyof foldersUpdateFolderErrors];

export type foldersUpdateFolderResponses = {
    /**
     * Successful Response
     */
    200: FolderPublic;
};

export type foldersUpdateFolderResponse = foldersUpdateFolderResponses[keyof foldersUpdateFolderResponses];

export type documentsReadDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
        /**
         * Folder Id
         */
        folder_id?: string | null;
        /**
         * Root Only
         */
        root_only?: boolean;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/';
};

export type documentsReadDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentsError = documentsReadDocumentsErrors[keyof documentsReadDocumentsErrors];

export type documentsReadDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentsPublic;
};

export type documentsReadDocumentsResponse = documentsReadDocumentsResponses[keyof documentsReadDocumentsResponses];

export type documentsCreateDocumentData = {
    body: DocumentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/documents/';
};

export type documentsCreateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsCreateDocumentError = documentsCreateDocumentErrors[keyof documentsCreateDocumentErrors];

export type documentsCreateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsCreateDocumentResponse = documentsCreateDocumentResponses[keyof documentsCreateDocumentResponses];

export type documentsReadRecentDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/recent';
};

export type documentsReadRecentDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadRecentDocumentsError = documentsReadRecentDocumentsErrors[keyof documentsReadRecentDocumentsErrors];

export type documentsReadRecentDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentsPublic;
};

export type documentsReadRecentDocumentsResponse = documentsReadRecentDocumentsResponses[keyof documentsReadRecentDocumentsResponses];

export type documentsReadSharedWithMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/documents/shared-with-me';
};

export type documentsReadSharedWithMeResponses = {
    /**
     * Successful Response
     */
    200: SharedWithMe;
};

export type documentsReadSharedWithMeResponse = documentsReadSharedWithMeResponses[keyof documentsReadSharedWithMeResponses];

export type documentsReadEmbeddingSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/documents/embeddings/summary';
};

export type documentsReadEmbeddingSummaryResponses = {
    /**
     * Successful Response
     */
    200: EmbeddingSummary;
};

export type documentsReadEmbeddingSummaryResponse = documentsReadEmbeddingSummaryResponses[keyof documentsReadEmbeddingSummaryResponses];

export type documentsDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type documentsDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsDeleteDocumentError = documentsDeleteDocumentErrors[keyof documentsDeleteDocumentErrors];

export type documentsDeleteDocumentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type documentsDeleteDocumentResponse = documentsDeleteDocumentResponses[keyof documentsDeleteDocumentResponses];

export type documentsReadDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type documentsReadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentError = documentsReadDocumentErrors[keyof documentsReadDocumentErrors];

export type documentsReadDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsReadDocumentResponse = documentsReadDocumentResponses[keyof documentsReadDocumentResponses];

export type documentsUpdateDocumentData = {
    body: DocumentUpdate;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type documentsUpdateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsUpdateDocumentError = documentsUpdateDocumentErrors[keyof documentsUpdateDocumentErrors];

export type documentsUpdateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsUpdateDocumentResponse = documentsUpdateDocumentResponses[keyof documentsUpdateDocumentResponses];

export type documentsMoveDocumentData = {
    body: DocumentMove;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/move';
};

export type documentsMoveDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsMoveDocumentError = documentsMoveDocumentErrors[keyof documentsMoveDocumentErrors];

export type documentsMoveDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsMoveDocumentResponse = documentsMoveDocumentResponses[keyof documentsMoveDocumentResponses];

export type documentsReadDocumentSharesData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/shares';
};

export type documentsReadDocumentSharesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentSharesError = documentsReadDocumentSharesErrors[keyof documentsReadDocumentSharesErrors];

export type documentsReadDocumentSharesResponses = {
    /**
     * Successful Response
     */
    200: DocumentSharesPublic;
};

export type documentsReadDocumentSharesResponse = documentsReadDocumentSharesResponses[keyof documentsReadDocumentSharesResponses];

export type documentsShareDocumentData = {
    body: DocumentShareCreate;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/shares';
};

export type documentsShareDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsShareDocumentError = documentsShareDocumentErrors[keyof documentsShareDocumentErrors];

export type documentsShareDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentSharePublic;
};

export type documentsShareDocumentResponse = documentsShareDocumentResponses[keyof documentsShareDocumentResponses];

export type documentsUnshareDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/shares/{user_id}';
};

export type documentsUnshareDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsUnshareDocumentError = documentsUnshareDocumentErrors[keyof documentsUnshareDocumentErrors];

export type documentsUnshareDocumentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type documentsUnshareDocumentResponse = documentsUnshareDocumentResponses[keyof documentsUnshareDocumentResponses];

export type documentsUpdateDocumentShareData = {
    body: DocumentShareUpdate;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/shares/{user_id}';
};

export type documentsUpdateDocumentShareErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsUpdateDocumentShareError = documentsUpdateDocumentShareErrors[keyof documentsUpdateDocumentShareErrors];

export type documentsUpdateDocumentShareResponses = {
    /**
     * Successful Response
     */
    200: DocumentSharePublic;
};

export type documentsUpdateDocumentShareResponse = documentsUpdateDocumentShareResponses[keyof documentsUpdateDocumentShareResponses];

export type documentsReadDocumentEmbeddingsData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/embeddings';
};

export type documentsReadDocumentEmbeddingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentEmbeddingsError = documentsReadDocumentEmbeddingsErrors[keyof documentsReadDocumentEmbeddingsErrors];

export type documentsReadDocumentEmbeddingsResponses = {
    /**
     * Successful Response
     */
    200: DocumentEmbeddingsPublic;
};

export type documentsReadDocumentEmbeddingsResponse = documentsReadDocumentEmbeddingsResponses[keyof documentsReadDocumentEmbeddingsResponses];

export type documentsReindexAllEmbeddingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/documents/embeddings/reindex-all';
};

export type documentsReindexAllEmbeddingsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type documentsReindexAllEmbeddingsResponse = documentsReindexAllEmbeddingsResponses[keyof documentsReindexAllEmbeddingsResponses];

export type documentsRegenerateDocumentEmbeddingsData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/embeddings/regenerate';
};

export type documentsRegenerateDocumentEmbeddingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsRegenerateDocumentEmbeddingsError = documentsRegenerateDocumentEmbeddingsErrors[keyof documentsRegenerateDocumentEmbeddingsErrors];

export type documentsRegenerateDocumentEmbeddingsResponses = {
    /**
     * Successful Response
     */
    200: EmbeddingJobPublic;
};

export type documentsRegenerateDocumentEmbeddingsResponse = documentsRegenerateDocumentEmbeddingsResponses[keyof documentsRegenerateDocumentEmbeddingsResponses];

export type attachmentsReadAttachmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
        /**
         * Document Id
         */
        document_id?: string | null;
    };
    url: '/api/v1/attachments/';
};

export type attachmentsReadAttachmentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsReadAttachmentsError = attachmentsReadAttachmentsErrors[keyof attachmentsReadAttachmentsErrors];

export type attachmentsReadAttachmentsResponses = {
    /**
     * Successful Response
     */
    200: AttachmentsPublic;
};

export type attachmentsReadAttachmentsResponse = attachmentsReadAttachmentsResponses[keyof attachmentsReadAttachmentsResponses];

export type attachmentsUploadAttachmentData = {
    body: Body_attachments_upload_attachment;
    path?: never;
    query?: never;
    url: '/api/v1/attachments/';
};

export type attachmentsUploadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsUploadAttachmentError = attachmentsUploadAttachmentErrors[keyof attachmentsUploadAttachmentErrors];

export type attachmentsUploadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: AttachmentPublic;
};

export type attachmentsUploadAttachmentResponse = attachmentsUploadAttachmentResponses[keyof attachmentsUploadAttachmentResponses];

export type attachmentsDeleteAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsDeleteAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDeleteAttachmentError = attachmentsDeleteAttachmentErrors[keyof attachmentsDeleteAttachmentErrors];

export type attachmentsDeleteAttachmentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type attachmentsDeleteAttachmentResponse = attachmentsDeleteAttachmentResponses[keyof attachmentsDeleteAttachmentResponses];

export type attachmentsReadAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsReadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsReadAttachmentError = attachmentsReadAttachmentErrors[keyof attachmentsReadAttachmentErrors];

export type attachmentsReadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: AttachmentPublic;
};

export type attachmentsReadAttachmentResponse = attachmentsReadAttachmentResponses[keyof attachmentsReadAttachmentResponses];

export type attachmentsDownloadAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}/download';
};

export type attachmentsDownloadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDownloadAttachmentError = attachmentsDownloadAttachmentErrors[keyof attachmentsDownloadAttachmentErrors];

export type attachmentsDownloadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type importsReadImportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
        /**
         * Status
         */
        status?: ImportStatus | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/imports/';
};

export type importsReadImportsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsReadImportsError = importsReadImportsErrors[keyof importsReadImportsErrors];

export type importsReadImportsResponses = {
    /**
     * Successful Response
     */
    200: ImportJobsPublic;
};

export type importsReadImportsResponse = importsReadImportsResponses[keyof importsReadImportsResponses];

export type importsCreateImportData = {
    body: Body_imports_create_import;
    path?: never;
    query?: never;
    url: '/api/v1/imports/';
};

export type importsCreateImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsCreateImportError = importsCreateImportErrors[keyof importsCreateImportErrors];

export type importsCreateImportResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type importsCreateImportResponse = importsCreateImportResponses[keyof importsCreateImportResponses];

export type importsDeleteImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}';
};

export type importsDeleteImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsDeleteImportError = importsDeleteImportErrors[keyof importsDeleteImportErrors];

export type importsDeleteImportResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type importsDeleteImportResponse = importsDeleteImportResponses[keyof importsDeleteImportResponses];

export type importsReadImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}';
};

export type importsReadImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsReadImportError = importsReadImportErrors[keyof importsReadImportErrors];

export type importsReadImportResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type importsReadImportResponse = importsReadImportResponses[keyof importsReadImportResponses];

export type importsRetryImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/retry';
};

export type importsRetryImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsRetryImportError = importsRetryImportErrors[keyof importsRetryImportErrors];

export type importsRetryImportResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type importsRetryImportResponse = importsRetryImportResponses[keyof importsRetryImportResponses];

export type importsCancelImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{import_id}/cancel';
};

export type importsCancelImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type importsCancelImportError = importsCancelImportErrors[keyof importsCancelImportErrors];

export type importsCancelImportResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type importsCancelImportResponse = importsCancelImportResponses[keyof importsCancelImportResponses];

export type apiKeysReadApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/api-keys/';
};

export type apiKeysReadApiKeysResponses = {
    /**
     * Successful Response
     */
    200: ApiKeysPublic;
};

export type apiKeysReadApiKeysResponse = apiKeysReadApiKeysResponses[keyof apiKeysReadApiKeysResponses];

export type apiKeysCreateApiKeyData = {
    body: ApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/api-keys/';
};

export type apiKeysCreateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type apiKeysCreateApiKeyError = apiKeysCreateApiKeyErrors[keyof apiKeysCreateApiKeyErrors];

export type apiKeysCreateApiKeyResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyCreated;
};

export type apiKeysCreateApiKeyResponse = apiKeysCreateApiKeyResponses[keyof apiKeysCreateApiKeyResponses];

export type apiKeysRevokeApiKeyData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/api-keys/{key_id}';
};

export type apiKeysRevokeApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type apiKeysRevokeApiKeyError = apiKeysRevokeApiKeyErrors[keyof apiKeysRevokeApiKeyErrors];

export type apiKeysRevokeApiKeyResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type apiKeysRevokeApiKeyResponse = apiKeysRevokeApiKeyResponses[keyof apiKeysRevokeApiKeyResponses];

export type apiKeysUpdateApiKeyData = {
    body: ApiKeyUpdate;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/api-keys/{key_id}';
};

export type apiKeysUpdateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type apiKeysUpdateApiKeyError = apiKeysUpdateApiKeyErrors[keyof apiKeysUpdateApiKeyErrors];

export type apiKeysUpdateApiKeyResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyPublic;
};

export type apiKeysUpdateApiKeyResponse = apiKeysUpdateApiKeyResponses[keyof apiKeysUpdateApiKeyResponses];

export type searchSearchDocumentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/search/';
};

export type searchSearchDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type searchSearchDocumentsError = searchSearchDocumentsErrors[keyof searchSearchDocumentsErrors];

export type searchSearchDocumentsResponses = {
    /**
     * Successful Response
     */
    200: SearchResults;
};

export type searchSearchDocumentsResponse = searchSearchDocumentsResponses[keyof searchSearchDocumentsResponses];

export type searchRetrieveDocumentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Bm25
         */
        bm25?: boolean;
        /**
         * Vector
         */
        vector?: boolean;
        /**
         * Targets
         */
        targets?: Array<EmbeddingKind>;
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Rrf K
         */
        rrf_k?: number | null;
        /**
         * Candidates Per Source
         */
        candidates_per_source?: number | null;
    };
    url: '/api/v1/search/retrieve';
};

export type searchRetrieveDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type searchRetrieveDocumentsError = searchRetrieveDocumentsErrors[keyof searchRetrieveDocumentsErrors];

export type searchRetrieveDocumentsResponses = {
    /**
     * Successful Response
     */
    200: RetrievalResults;
};

export type searchRetrieveDocumentsResponse = searchRetrieveDocumentsResponses[keyof searchRetrieveDocumentsResponses];

export type askAskQuestionData = {
    body: AskRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ask/';
};

export type askAskQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type askAskQuestionError = askAskQuestionErrors[keyof askAskQuestionErrors];

export type askAskQuestionResponses = {
    /**
     * Successful Response
     */
    200: AskAnswer;
};

export type askAskQuestionResponse = askAskQuestionResponses[keyof askAskQuestionResponses];

export type askAskQuestionStreamData = {
    body: AskRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ask/stream';
};

export type askAskQuestionStreamErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type askAskQuestionStreamError = askAskQuestionStreamErrors[keyof askAskQuestionStreamErrors];

export type askAskQuestionStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type workersReadWorkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workers/';
};

export type workersReadWorkersResponses = {
    /**
     * Successful Response
     */
    200: WorkersPublic;
};

export type workersReadWorkersResponse = workersReadWorkersResponses[keyof workersReadWorkersResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
