"""hybrid retrieval and document imports

Revision ID: 72d563bcfe03
Revises: 70518a1b6b68
Create Date: 2026-09-12 10:21:28.265570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '72d563bcfe03'
down_revision = '70518a1b6b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parser', sa.String(length=32), nullable=True),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index('ix_importjob_namespace', 'importjob', ['namespace_id'], unique=False)
    op.create_index('ix_importjob_status_created', 'importjob', ['status', 'created_at'], unique=False)
    op.add_column('document', sa.Column('source_attachment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_document_source_attachment', 'document', 'attachment',
        ['source_attachment_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_source_attachment', 'document', type_='foreignkey')
    op.drop_column('document', 'source_attachment_id')
    op.drop_index('ix_importjob_status_created', table_name='importjob')
    op.drop_index('ix_importjob_namespace', table_name='importjob')
    op.drop_table('importjob')
    # ### end Alembic commands ###
