"""data sources: admin config and per-user connections

Revision ID: 7a109a76b1c6
Revises: f7b3d52c9014
Create Date: 2026-09-14 00:08:50.334604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a109a76b1c6'
down_revision = 'f7b3d52c9014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasourceconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasourceconfig_source_type'), 'datasourceconfig', ['source_type'], unique=True)
    op.create_table('datasourceconnection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', name='uq_datasource_user_source')
    )
    op.create_index(op.f('ix_datasourceconnection_source_type'), 'datasourceconnection', ['source_type'], unique=False)
    op.create_index(op.f('ix_datasourceconnection_user_id'), 'datasourceconnection', ['user_id'], unique=False)
    # Autogenerate also proposed dropping ix_authcode_user_purpose and the
    # ck_shareinvitation_one_target check constraint. Both are real and
    # deliberate, created by earlier migrations and invisible to the models,
    # so it sees them as drift. Dropping the check would quietly permit a share
    # invitation that targets a page and a space at once.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasourceconnection_user_id'), table_name='datasourceconnection')
    op.drop_index(op.f('ix_datasourceconnection_source_type'), table_name='datasourceconnection')
    op.drop_table('datasourceconnection')
    op.drop_index(op.f('ix_datasourceconfig_source_type'), table_name='datasourceconfig')
    op.drop_table('datasourceconfig')
    # ### end Alembic commands ###
