import { expect, test } from "@playwright/test"

/**
 * The signed-out pages: the landing half of sign-in, and the two policies.
 *
 * All three have to work with no session at all, which is the thing most
 * likely to break them.
 */

test.describe("Signed out", () => {
  test.use({ storageState: { cookies: [], origins: [] } })

  test("the sign-in page leads with what this is", async ({ page }) => {
    await page.goto("/login")

    await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible()
    await expect(page.getByTestId("email-input")).toBeVisible()
    await expect(page.getByTestId("password-input")).toBeVisible()
    await expect(
      page.getByRole("heading", { name: /one question away/i }),
    ).toBeVisible()
  })

  test("the policies are reachable without signing in", async ({ page }) => {
    await page.goto("/privacy")
    await expect(
      page.getByRole("heading", { name: "Privacy Policy", level: 1 }),
    ).toBeVisible()
    await expect(page.getByText(/what is sent to them/i)).toBeVisible()

    await page.goto("/terms")
    await expect(
      page.getByRole("heading", { name: "Terms of Service", level: 1 }),
    ).toBeVisible()
    // The one claim a user of an AI product most needs to see.
    await expect(
      page.getByText(/Answers are generated by a language model and can be wrong/i),
    ).toBeVisible()
  })

  test("sign-in links to both, and each links back", async ({ page }) => {
    await page.goto("/login")
    await page.getByRole("link", { name: "Privacy Policy" }).click()
    await expect(page).toHaveURL(/\/privacy/)

    await page.getByRole("link", { name: "Terms", exact: true }).first().click()
    await expect(page).toHaveURL(/\/terms/)

    await page.getByRole("link", { name: "Back" }).click()
    await expect(page).toHaveURL(/\/login/)
  })

  test("the policies work on a phone", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto("/terms")
    await expect(
      page.getByRole("heading", { name: "Terms of Service", level: 1 }),
    ).toBeVisible()

    const overflow = await page.evaluate(
      () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
    )
    expect(overflow, "the page scrolls sideways on a phone").toBeLessThanOrEqual(1)
  })
})
