/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAskRouteImport } from './routes/_layout/ask'
import { Route as LayoutImportsRouteImport } from './routes/_layout/imports'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSharedRouteImport } from './routes/_layout/shared'
import { Route as LayoutSNamespaceSlugRouteImport } from './routes/_layout/s/$namespaceSlug'
import { Route as LayoutSNamespaceSlugIndexRouteImport } from './routes/_layout/s/$namespaceSlug/index'
import { Route as LayoutSNamespaceSlugSettingsRouteImport } from './routes/_layout/s/$namespaceSlug/settings'
import { Route as LayoutSNamespaceSlugDDocumentIdRouteImport } from './routes/_layout/s/$namespaceSlug/d/$documentId'
import { Route as LayoutSNamespaceSlugFFolderIdRouteImport } from './routes/_layout/s/$namespaceSlug/f/$folderId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAskRoute = LayoutAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportsRoute = LayoutImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSharedRoute = LayoutSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSNamespaceSlugRoute = LayoutSNamespaceSlugRouteImport.update({
  id: '/s/$namespaceSlug',
  path: '/s/$namespaceSlug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSNamespaceSlugIndexRoute =
  LayoutSNamespaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugSettingsRoute =
  LayoutSNamespaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugDDocumentIdRoute =
  LayoutSNamespaceSlugDDocumentIdRouteImport.update({
    id: '/d/$documentId',
    path: '/d/$documentId',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugFFolderIdRoute =
  LayoutSNamespaceSlugFFolderIdRouteImport.update({
    id: '/f/$folderId',
    path: '/f/$folderId',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ask': typeof LayoutAskRoute
  '/imports': typeof LayoutImportsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/shared': typeof LayoutSharedRoute
  '/s/$namespaceSlug': typeof LayoutSNamespaceSlugRouteWithChildren
  '/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/s/$namespaceSlug/': typeof LayoutSNamespaceSlugIndexRoute
  '/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ask': typeof LayoutAskRoute
  '/imports': typeof LayoutImportsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/shared': typeof LayoutSharedRoute
  '/': typeof LayoutIndexRoute
  '/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/s/$namespaceSlug': typeof LayoutSNamespaceSlugIndexRoute
  '/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ask': typeof LayoutAskRoute
  '/_layout/imports': typeof LayoutImportsRoute
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shared': typeof LayoutSharedRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/s/$namespaceSlug': typeof LayoutSNamespaceSlugRouteWithChildren
  '/_layout/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/_layout/s/$namespaceSlug/': typeof LayoutSNamespaceSlugIndexRoute
  '/_layout/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/_layout/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/ask'
    | '/imports'
    | '/playground'
    | '/search'
    | '/settings'
    | '/shared'
    | '/s/$namespaceSlug'
    | '/s/$namespaceSlug/settings'
    | '/s/$namespaceSlug/'
    | '/s/$namespaceSlug/d/$documentId'
    | '/s/$namespaceSlug/f/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/ask'
    | '/imports'
    | '/playground'
    | '/search'
    | '/settings'
    | '/shared'
    | '/'
    | '/s/$namespaceSlug/settings'
    | '/s/$namespaceSlug'
    | '/s/$namespaceSlug/d/$documentId'
    | '/s/$namespaceSlug/f/$folderId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/ask'
    | '/_layout/imports'
    | '/_layout/playground'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/shared'
    | '/_layout/'
    | '/_layout/s/$namespaceSlug'
    | '/_layout/s/$namespaceSlug/settings'
    | '/_layout/s/$namespaceSlug/'
    | '/_layout/s/$namespaceSlug/d/$documentId'
    | '/_layout/s/$namespaceSlug/f/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ask': {
      id: '/_layout/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof LayoutAskRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/imports': {
      id: '/_layout/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof LayoutImportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shared': {
      id: '/_layout/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof LayoutSharedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/s/$namespaceSlug': {
      id: '/_layout/s/$namespaceSlug'
      path: '/s/$namespaceSlug'
      fullPath: '/s/$namespaceSlug'
      preLoaderRoute: typeof LayoutSNamespaceSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/s/$namespaceSlug/': {
      id: '/_layout/s/$namespaceSlug/'
      path: '/'
      fullPath: '/s/$namespaceSlug/'
      preLoaderRoute: typeof LayoutSNamespaceSlugIndexRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/settings': {
      id: '/_layout/s/$namespaceSlug/settings'
      path: '/settings'
      fullPath: '/s/$namespaceSlug/settings'
      preLoaderRoute: typeof LayoutSNamespaceSlugSettingsRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/d/$documentId': {
      id: '/_layout/s/$namespaceSlug/d/$documentId'
      path: '/d/$documentId'
      fullPath: '/s/$namespaceSlug/d/$documentId'
      preLoaderRoute: typeof LayoutSNamespaceSlugDDocumentIdRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/f/$folderId': {
      id: '/_layout/s/$namespaceSlug/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/s/$namespaceSlug/f/$folderId'
      preLoaderRoute: typeof LayoutSNamespaceSlugFFolderIdRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
  }
}

interface LayoutSNamespaceSlugRouteChildren {
  LayoutSNamespaceSlugSettingsRoute: typeof LayoutSNamespaceSlugSettingsRoute
  LayoutSNamespaceSlugIndexRoute: typeof LayoutSNamespaceSlugIndexRoute
  LayoutSNamespaceSlugDDocumentIdRoute: typeof LayoutSNamespaceSlugDDocumentIdRoute
  LayoutSNamespaceSlugFFolderIdRoute: typeof LayoutSNamespaceSlugFFolderIdRoute
}

const LayoutSNamespaceSlugRouteChildren: LayoutSNamespaceSlugRouteChildren = {
  LayoutSNamespaceSlugSettingsRoute: LayoutSNamespaceSlugSettingsRoute,
  LayoutSNamespaceSlugIndexRoute: LayoutSNamespaceSlugIndexRoute,
  LayoutSNamespaceSlugDDocumentIdRoute: LayoutSNamespaceSlugDDocumentIdRoute,
  LayoutSNamespaceSlugFFolderIdRoute: LayoutSNamespaceSlugFFolderIdRoute,
}

const LayoutSNamespaceSlugRouteWithChildren =
  LayoutSNamespaceSlugRoute._addFileChildren(LayoutSNamespaceSlugRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAskRoute: typeof LayoutAskRoute
  LayoutImportsRoute: typeof LayoutImportsRoute
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSharedRoute: typeof LayoutSharedRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSNamespaceSlugRoute: typeof LayoutSNamespaceSlugRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAskRoute: LayoutAskRoute,
  LayoutImportsRoute: LayoutImportsRoute,
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSharedRoute: LayoutSharedRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSNamespaceSlugRoute: LayoutSNamespaceSlugRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
