/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAskRouteImport } from './routes/_layout/ask'
import { Route as LayoutCaptureRouteImport } from './routes/_layout/capture'
import { Route as LayoutDataSourcesRouteImport } from './routes/_layout/data-sources'
import { Route as LayoutImportsRouteImport } from './routes/_layout/imports'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSharedRouteImport } from './routes/_layout/shared'
import { Route as LayoutUsageRouteImport } from './routes/_layout/usage'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LayoutAgentsIndexRouteImport } from './routes/_layout/agents.index'
import { Route as LayoutAgentsAgentIdRouteImport } from './routes/_layout/agents.$agentId'
import { Route as LayoutSNamespaceSlugRouteImport } from './routes/_layout/s/$namespaceSlug'
import { Route as LayoutSNamespaceSlugIndexRouteImport } from './routes/_layout/s/$namespaceSlug/index'
import { Route as LayoutSNamespaceSlugSettingsRouteImport } from './routes/_layout/s/$namespaceSlug/settings'
import { Route as LayoutSNamespaceSlugDDocumentIdRouteImport } from './routes/_layout/s/$namespaceSlug/d/$documentId'
import { Route as LayoutSNamespaceSlugFFolderIdRouteImport } from './routes/_layout/s/$namespaceSlug/f/$folderId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAskRoute = LayoutAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCaptureRoute = LayoutCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDataSourcesRoute = LayoutDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportsRoute = LayoutImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSharedRoute = LayoutSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsageRoute = LayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAgentsIndexRoute = LayoutAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsAgentIdRoute = LayoutAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSNamespaceSlugRoute = LayoutSNamespaceSlugRouteImport.update({
  id: '/s/$namespaceSlug',
  path: '/s/$namespaceSlug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSNamespaceSlugIndexRoute =
  LayoutSNamespaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugSettingsRoute =
  LayoutSNamespaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugDDocumentIdRoute =
  LayoutSNamespaceSlugDDocumentIdRouteImport.update({
    id: '/d/$documentId',
    path: '/d/$documentId',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)
const LayoutSNamespaceSlugFFolderIdRoute =
  LayoutSNamespaceSlugFFolderIdRouteImport.update({
    id: '/f/$folderId',
    path: '/f/$folderId',
    getParentRoute: () => LayoutSNamespaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/ask': typeof LayoutAskRoute
  '/capture': typeof LayoutCaptureRoute
  '/data-sources': typeof LayoutDataSourcesRoute
  '/imports': typeof LayoutImportsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/shared': typeof LayoutSharedRoute
  '/usage': typeof LayoutUsageRoute
  '/p/$slug': typeof PSlugRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/s/$namespaceSlug': typeof LayoutSNamespaceSlugRouteWithChildren
  '/agents/': typeof LayoutAgentsIndexRoute
  '/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/s/$namespaceSlug/': typeof LayoutSNamespaceSlugIndexRoute
  '/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/ask': typeof LayoutAskRoute
  '/capture': typeof LayoutCaptureRoute
  '/data-sources': typeof LayoutDataSourcesRoute
  '/imports': typeof LayoutImportsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/shared': typeof LayoutSharedRoute
  '/usage': typeof LayoutUsageRoute
  '/p/$slug': typeof PSlugRoute
  '/': typeof LayoutIndexRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/agents': typeof LayoutAgentsIndexRoute
  '/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/s/$namespaceSlug': typeof LayoutSNamespaceSlugIndexRoute
  '/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ask': typeof LayoutAskRoute
  '/_layout/capture': typeof LayoutCaptureRoute
  '/_layout/data-sources': typeof LayoutDataSourcesRoute
  '/_layout/imports': typeof LayoutImportsRoute
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shared': typeof LayoutSharedRoute
  '/_layout/usage': typeof LayoutUsageRoute
  '/p/$slug': typeof PSlugRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/_layout/s/$namespaceSlug': typeof LayoutSNamespaceSlugRouteWithChildren
  '/_layout/agents/': typeof LayoutAgentsIndexRoute
  '/_layout/s/$namespaceSlug/settings': typeof LayoutSNamespaceSlugSettingsRoute
  '/_layout/s/$namespaceSlug/': typeof LayoutSNamespaceSlugIndexRoute
  '/_layout/s/$namespaceSlug/d/$documentId': typeof LayoutSNamespaceSlugDDocumentIdRoute
  '/_layout/s/$namespaceSlug/f/$folderId': typeof LayoutSNamespaceSlugFFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/imprint'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/ask'
    | '/capture'
    | '/data-sources'
    | '/imports'
    | '/playground'
    | '/search'
    | '/settings'
    | '/shared'
    | '/usage'
    | '/p/$slug'
    | '/agents/$agentId'
    | '/s/$namespaceSlug'
    | '/agents/'
    | '/s/$namespaceSlug/settings'
    | '/s/$namespaceSlug/'
    | '/s/$namespaceSlug/d/$documentId'
    | '/s/$namespaceSlug/f/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/imprint'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/ask'
    | '/capture'
    | '/data-sources'
    | '/imports'
    | '/playground'
    | '/search'
    | '/settings'
    | '/shared'
    | '/usage'
    | '/p/$slug'
    | '/'
    | '/agents/$agentId'
    | '/agents'
    | '/s/$namespaceSlug/settings'
    | '/s/$namespaceSlug'
    | '/s/$namespaceSlug/d/$documentId'
    | '/s/$namespaceSlug/f/$folderId'
  id:
    | '__root__'
    | '/_layout'
    | '/forgot-password'
    | '/imprint'
    | '/invite'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/ask'
    | '/_layout/capture'
    | '/_layout/data-sources'
    | '/_layout/imports'
    | '/_layout/playground'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/shared'
    | '/_layout/usage'
    | '/p/$slug'
    | '/_layout/'
    | '/_layout/agents/$agentId'
    | '/_layout/s/$namespaceSlug'
    | '/_layout/agents/'
    | '/_layout/s/$namespaceSlug/settings'
    | '/_layout/s/$namespaceSlug/'
    | '/_layout/s/$namespaceSlug/d/$documentId'
    | '/_layout/s/$namespaceSlug/f/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImprintRoute: typeof ImprintRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ask': {
      id: '/_layout/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof LayoutAskRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/capture': {
      id: '/_layout/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof LayoutCaptureRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/data-sources': {
      id: '/_layout/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof LayoutDataSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/imports': {
      id: '/_layout/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof LayoutImportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shared': {
      id: '/_layout/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof LayoutSharedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usage': {
      id: '/_layout/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof LayoutUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/agents/': {
      id: '/_layout/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof LayoutAgentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents/$agentId': {
      id: '/_layout/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof LayoutAgentsAgentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/s/$namespaceSlug': {
      id: '/_layout/s/$namespaceSlug'
      path: '/s/$namespaceSlug'
      fullPath: '/s/$namespaceSlug'
      preLoaderRoute: typeof LayoutSNamespaceSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/s/$namespaceSlug/': {
      id: '/_layout/s/$namespaceSlug/'
      path: '/'
      fullPath: '/s/$namespaceSlug/'
      preLoaderRoute: typeof LayoutSNamespaceSlugIndexRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/settings': {
      id: '/_layout/s/$namespaceSlug/settings'
      path: '/settings'
      fullPath: '/s/$namespaceSlug/settings'
      preLoaderRoute: typeof LayoutSNamespaceSlugSettingsRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/d/$documentId': {
      id: '/_layout/s/$namespaceSlug/d/$documentId'
      path: '/d/$documentId'
      fullPath: '/s/$namespaceSlug/d/$documentId'
      preLoaderRoute: typeof LayoutSNamespaceSlugDDocumentIdRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
    '/_layout/s/$namespaceSlug/f/$folderId': {
      id: '/_layout/s/$namespaceSlug/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/s/$namespaceSlug/f/$folderId'
      preLoaderRoute: typeof LayoutSNamespaceSlugFFolderIdRouteImport
      parentRoute: typeof LayoutSNamespaceSlugRoute
    }
  }
}

interface LayoutSNamespaceSlugRouteChildren {
  LayoutSNamespaceSlugSettingsRoute: typeof LayoutSNamespaceSlugSettingsRoute
  LayoutSNamespaceSlugIndexRoute: typeof LayoutSNamespaceSlugIndexRoute
  LayoutSNamespaceSlugDDocumentIdRoute: typeof LayoutSNamespaceSlugDDocumentIdRoute
  LayoutSNamespaceSlugFFolderIdRoute: typeof LayoutSNamespaceSlugFFolderIdRoute
}

const LayoutSNamespaceSlugRouteChildren: LayoutSNamespaceSlugRouteChildren = {
  LayoutSNamespaceSlugSettingsRoute: LayoutSNamespaceSlugSettingsRoute,
  LayoutSNamespaceSlugIndexRoute: LayoutSNamespaceSlugIndexRoute,
  LayoutSNamespaceSlugDDocumentIdRoute: LayoutSNamespaceSlugDDocumentIdRoute,
  LayoutSNamespaceSlugFFolderIdRoute: LayoutSNamespaceSlugFFolderIdRoute,
}

const LayoutSNamespaceSlugRouteWithChildren =
  LayoutSNamespaceSlugRoute._addFileChildren(LayoutSNamespaceSlugRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAskRoute: typeof LayoutAskRoute
  LayoutCaptureRoute: typeof LayoutCaptureRoute
  LayoutDataSourcesRoute: typeof LayoutDataSourcesRoute
  LayoutImportsRoute: typeof LayoutImportsRoute
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSharedRoute: typeof LayoutSharedRoute
  LayoutUsageRoute: typeof LayoutUsageRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAgentsAgentIdRoute: typeof LayoutAgentsAgentIdRoute
  LayoutSNamespaceSlugRoute: typeof LayoutSNamespaceSlugRouteWithChildren
  LayoutAgentsIndexRoute: typeof LayoutAgentsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAskRoute: LayoutAskRoute,
  LayoutCaptureRoute: LayoutCaptureRoute,
  LayoutDataSourcesRoute: LayoutDataSourcesRoute,
  LayoutImportsRoute: LayoutImportsRoute,
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSharedRoute: LayoutSharedRoute,
  LayoutUsageRoute: LayoutUsageRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAgentsAgentIdRoute: LayoutAgentsAgentIdRoute,
  LayoutSNamespaceSlugRoute: LayoutSNamespaceSlugRouteWithChildren,
  LayoutAgentsIndexRoute: LayoutAgentsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImprintRoute: ImprintRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
